openapi: 3.0.0
info:
  title: ArgentBank Transactions API
  version: 1.0.0
  description: API pour gérer les transactions d’un utilisateur connecté sur l’application ArgentBank.

servers:
  - url: http://localhost:3001/api/v1

paths:
  /transactions/{accountId}:
    get:
      summary: Liste des transactions pour un compte utilisateur
      description: Retourne toutes les transactions associées à un compte bancaire de l'utilisateur connecté.
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: L’identifiant unique du compte bancaire
        - name: month
          in: query
          required: false
          schema:
            type: string
            example: "2025-07"
          description: Filtrer les transactions par mois (format YYYY-MM)
      responses:
        '200':
          description: Liste des transactions retournée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transaction'
        '401':
          description: Utilisateur non autorisé
        '404':
          description: Compte non trouvé
        '500':
          description : Erreur serveur

  /transactions/{accountId}/{transactionId}:
    get:
      summary: Détails d'une transaction
      description: Retourne les détails d’une transaction spécifique pour un compte donné.
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails de la transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '401':
          description: Utilisateur non autorisé
        '404':
          description: Transaction ou compte introuvable
        '500':
          description : Erreur serveur

    put:
      summary: Modifier une transaction
      description: Permet de mettre à jour le libellé ou la note d’une transaction spécifique.
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
        - name: transactionId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: string
                  description: Libellé de la transaction
                note:
                  type: string
                  description: Note personnelle sur la transaction
      responses:
        '200':
          description: Transaction modifiée avec succès
        '400':
          description: Données invalides
        '401':
          description: Utilisateur non autorisé
        '404':
          description: Transaction non trouvée
        '500':
          description : Erreur serveur

components:
  schemas:
    Transaction:
      type: object
      properties:
        id:
          type: string
        accountId:
          type: string
        amount:
          type: number
          format: float
        type:
          type: string
          enum: [credit, debit]
        date:
          type: string
          format: date-time
        category:
          type: string
        label:
          type: string
        note:
          type: string
